name: Fly Deploy (Dev)
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  MAIL_USERNAME: 'emotionappdev2022@gmail.com'
on:
  push:
    branches:
      - development
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Print name
        run: echo "Hello $MAIL_USERNAME"
      - name: Print env
        run: printenv
      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
      - name: Run test
        run: python test.py

      
        
